name: WorldFuscator
version: ${project.build.version}
description: Worldfuscator Plugin
website: 
author: postremus
main: net.myplayplanet.worldfuscator.Plugin.WorldFuscatorImpl
depend: [ProtocolLib]
soft-depend: [WarGear, WorldGuard]