name: WorldFuscator
version: ${project.build.version}
description: Worldfuscator Plugin
website: myplayplanet.net
api-version: 1.13
author: postremus
main: net.myplayplanet.worldfuscator.Plugin.WorldFuscatorImpl
depend: [ProtocolLib]
soft-depend: [WarGear-Fight, WorldGuard]
