name: WorldFuscator
version: ${project.build.version}
description: Worldfuscator Plugin
website: 
author: postremus
main: de.pro_crafting.worldfuscator.Plugin.WorldFuscator_Impl
depend: [ProtocolLib, WorldGuard]